alter table bpm_manufacture_day_plan_item
    rename to bpm_manufacture_day_plan_line_item;
alter sequence bpm_manufacture_day_plan_item_id_sequence
    rename to bpm_manufacture_day_plan_line_item_id_sequence;